[2025-04-09T08:01:52.256+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_pipeline_modo_prueba.extract_grammy manual__2025-04-09T08:01:49.090864+00:00 [queued]>
[2025-04-09T08:01:52.267+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_pipeline_modo_prueba.extract_grammy manual__2025-04-09T08:01:49.090864+00:00 [queued]>
[2025-04-09T08:01:52.268+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-04-09T08:01:52.344+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): extract_grammy> on 2025-04-09 08:01:49.090864+00:00
[2025-04-09T08:01:52.350+0000] {standard_task_runner.py:60} INFO - Started process 56 to run task
[2025-04-09T08:01:52.353+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'etl_pipeline_modo_prueba', 'extract_grammy', 'manual__2025-04-09T08:01:49.090864+00:00', '--job-id', '100', '--raw', '--subdir', 'DAGS_FOLDER/etl_workflow.py', '--cfg-path', '/tmp/tmp1tlizh0y']
[2025-04-09T08:01:52.355+0000] {standard_task_runner.py:88} INFO - Job 100: Subtask extract_grammy
[2025-04-09T08:01:52.447+0000] {task_command.py:423} INFO - Running <TaskInstance: etl_pipeline_modo_prueba.extract_grammy manual__2025-04-09T08:01:49.090864+00:00 [running]> on host 55320d3f84c9
[2025-04-09T08:01:52.716+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='simon' AIRFLOW_CTX_DAG_ID='etl_pipeline_modo_prueba' AIRFLOW_CTX_TASK_ID='extract_grammy' AIRFLOW_CTX_EXECUTION_DATE='2025-04-09T08:01:49.090864+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-09T08:01:49.090864+00:00'
[2025-04-09T08:01:52.717+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-04-09T08:01:52.718+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /opt/***/scripts/extract_grammy.py']
[2025-04-09T08:01:52.738+0000] {subprocess.py:86} INFO - Output:
[2025-04-09T08:01:59.648+0000] {subprocess.py:93} INFO - ‚ùå Error inesperado: [Errno 13] Permission denied: '/opt/***/data/processed/grammy.parquet'
[2025-04-09T08:01:59.870+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-04-09T08:01:59.971+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=etl_pipeline_modo_prueba, task_id=extract_grammy, execution_date=20250409T080149, start_date=20250409T080152, end_date=20250409T080159
[2025-04-09T08:02:00.071+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-04-09T08:02:00.154+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
